version: 3

vars:
  # SERVICES: 
  #   sh: git show --name-only --oneline ${CIRCLE_SHA1} | awk -F"/" '/^services\// {print $2}' | grep -v README | sort -u
  # ALL_SERVICES:
  #   sh: for service in ./services/**/main.tf; do echo $service | cut -d/ -f3 | tr "\n" " "; done
  SERVICES:
    sh: git diff --name-only master... | grep 'services/' | cut -d/ -f2 | sort -u | tr '\n' ' '
  ALL_SERVICES:
    sh: find services -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | tr '\n' ' '
  

tasks:

  test:
    desc: print vars
    cmds:
      - echo "SERVICES:{{.SERVICES}}, ALL_SERVICES:{{.ALL_SERVICES}}"
  clean:
    desc: Remove terraform build files
    cmds:
      - find . -name .terraform | xargs rm -rf;

  init:
    desc: terraform init on new service changes found in git
    cmds:
      - |
        echo "Starting terraform init"; \
        for service in {{.SERVICES}}; do \
          echo $service; \
          terraform -chdir=./services/$service init; \
        done; \
        echo "Done running terraform init"; 
  
  plan:
    deps: [init]
    desc: terraform plan on new service changes found in git
    cmds:
      - |
        echo "Starting terraform plan"; \
        for service in {{.SERVICES}}; do \
          echo $service; \
          terraform -chdir=./services/$service plan; \
        done; \
        echo "Done running terraform plan"; 

  apply:
    deps: [clean, init]
    desc: terraform plan on new service changes found in git
    cmds:
      - |
        echo "Starting terraform apply"; \
        for service in {{.SERVICES}}; do \
          echo $service; \
          terraform -chdir=./services/$service apply; \
        done; \
        echo "Done running terraform plan";

  fmt:
    deps: [clean]
    desc: terraform fmt check only
    cmds:
      - |
        echo "Starting terraform fmt -check"; \
        for service in {{.SERVICES}}; do \
          terraform -chdir=./services/$service fmt -check=true -write=false -diff=true; \
        done; \
        echo "Done running terraform fmt"; 
  
  fmt-all:
    deps: [clean]
    desc: terraform fmt check only
    cmds:
      - |
        echo "Starting terraform fmt -check"; \
        for service in {{.ALL_SERVICES}}; do \
          terraform -chdir=./services/$service fmt -check=true -write=false -diff=true; \
        done; \
        echo "Done running terraform fmt-all"; 
  
  fmt-write:
    deps: [clean]
    desc: terraform fmt write
    cmds:
      - |
        echo "Starting terraform fmt-write"; \
        for service in {{.SERVICES}}; do \
          terraform -chdir=./services/$service fmt -write=true; \
        done; \
        echo "Done running terraform fmt-write"; 

  fmt-write-all:
    deps: [clean]
    desc: terraform fmt write all
    cmds:
      - |
        echo "Starting terraform fmt-write-all"; \
        for service in {{.ALL_SERVICES}}; do \
          terraform -chdir=./services/$service fmt -write=true; \
        done; \
        echo "Done running terraform fmt-write-all"; 

  validate:
    deps: [clean, init]
    desc: Validates terraform code
    cmds:
      - echo "Running terraform validate"
      - |
        for service in {{.SERVICES}}; do \
          terraform -chdir=./services/$service validate; \
        done; \
      - echo "Done running terraform validate"

  destroy:
    deps: [prompt]
    desc: terraform destroy
    prompt: "Are you sure you want to run this? It will destroy everything in {{.SERVICES}}"
    cmds:
      - |
        echo "Starting terraform destroy": \
        for service in {{.SERVICES}}: do \
          echo $service; \
          terraform -chdir=./services/$service destroy; \
        done; \
        echo "Done running terraform destroy";

  prompt:
    desc: universal prompt
    prompt: Are you sure?

  documentation:
    deps: [prompt]
    desc: generate terraform documentation
    cmds:
      - |
        echo "# KC Terraform Services" > ./services/README.md; \
        for service in {{.SERVICES}}; do \
          echo "* [`basename $service`](`basename $service`/README.md)" >> ./services/README.md; \
          echo "Generating docs for $service"; \
          terraform-docs  md table ./services/$service > ./services/$service/README.md; \
        done; \
        echo "## [Back](../README.md)" >> ./services/README.md \



          