version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  terraform: circleci/terraform@3.7.0

include:
  - local: ../orbs/orb.yml

anchors:
  - &context
    context:
      - circleci-secrets
      - slack-notifications
  - &branch_filter
    filters:
      branches:
        only:
          - kyle

workflows:
  # This workflow only runs if it was triggered by the top-level path-filtering job.
  terraform-ci-cd:
    jobs:
      - terraform_ci_job:
          name: terraform_validate
          mode: validate
          <<: *context
          <<: *branch_filter
      - terraform_ci_job:
          name: terraform_plan
          mode: plan
          <<: *context
          <<: *branch_filter
          requires:
            - terraform_validate
      - hold-for-apply:
          type: approval
          requires:
            - terraform_plan
      - terraform_ci_job:
          name: terraform_apply
          mode: apply
          <<: *context
          <<: *branch_filter
          requires:
            - hold-for-apply
