version: 2.1

orbs:
  # The continuation orb is required for this dynamic workflow
  continuation: circleci/continuation@0.3.1

# This job will run first to check for changes.
jobs:
  check_for_changes:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Check for changed services and decide to continue"
          command: |
            # This script determines if any Terraform services have changed.
            CHANGED_SERVICES=$(git diff-tree --no-commit-id --name-only -r "$CIRCLE_SHA1" | awk -F'/' '/^services\// {print $2}' | sort -u | tr '\n' ' ')
            
            if [ -n "$CHANGED_SERVICES" ]; then
              echo "Changes detected in services: $CHANGED_SERVICES"
              # If changes are found, trigger the second stage of the pipeline
              # by passing a parameter to the continue_config.yml file.
              continuation/continue:
                configuration_path: .circleci/continue_config.yml
                parameters: '{ "run_tf_workflow": true }'
            else
              echo "No changes detected in any services. Stopping pipeline."
            fi

# This is the initial workflow that will always run.
workflows:
  check_workflow:
    jobs:
      - check_for_changes:
          context: circleci-secrets # Add context for environment variables if needed
          filters:
            branches:
              only:
                - kyle